spring.application.name=compra-service

server.port=8083

spring.datasource.url=jdbc:h2:mem:compradb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

resilience4j.circuitbreaker.instances.historicoService.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.historicoService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.historicoService.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.historicoService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.historicoService.waitDurationInOpenState=10s